src/accounts/urls.py
from django.urls import path

from accounts.views import sign_up, logout_user, sign_in

app_name = "accounts"

urlpatterns = [
    path('sign-up/', sign_up, name="sign_up"),
    path('sign-in', sign_in, name="sign_in"),
    path('logout/', logout_user, name="logout")
]

src/shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shop import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include("accounts.urls"), name="accounts"),
                  path('store/', include('store.urls'), name="store")
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/store/urls.py
from django.urls import path

from store.views import index, product_detail, add_to_cart, cart, cart_delete

app_name = "store"

urlpatterns = [
    path('', index, name="index"),
    path('cart/', cart, name="cart"),
    path('cart/delete', cart_delete, name="cart_delete"),
    path('<str:slug>/product-detail/', product_detail, name="product_detail"),
    path('<str:slug>/product-detail/add-to-cart/', add_to_cart, name="add_to_cart")
]

src/accounts/models.py
from django.contrib.auth.models import AbstractUser


class Customer(AbstractUser):
    pass

src/store/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

from accounts.models import Customer


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField(default=0.00)
    stock = models.IntegerField(default=0)
    slug = models.CharField(max_length=100, name="slug", blank=False, null=False)
    description = models.TextField(blank=True)
    thumbnail = models.ImageField(upload_to="products", blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('store:product_detail', kwargs={'slug': self.slug})


class Order(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.product.name} - {self.user.username} - {self.quantity} "


class Cart(models.Model):
    user = models.OneToOneField(Customer, on_delete=models.CASCADE)
    orders = models.ManyToManyField(Order, related_name="Cart_Orders")

    def __str__(self) -> str:
        return f"{self.user.username} - {self.ordered} - {self.ordered_date}"

    def delete(self, *args, **kwargs):
        for order in self.orders.all():
            order.ordered = True
            order.ordered_date = timezone.now()
            order.save()

        self.orders.clear()

        super().delete(*args, **kwargs)

src/accounts/views.py
import logging

from django.contrib.auth import get_user_model, login, logout, authenticate
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

User = get_user_model()


# Create your views here.
def sign_up(request: HttpRequest) -> HttpResponse:
    context = {}
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            check_user = User.objects.get(username=username)
            if not check_user:
                user = User.objects.create_user(username=username, password=password)
                if user:
                    login(request=request, user=user)
                    return redirect('store:index')
            else:
                logging.error("username already exist, try with another one.")
                context['username_error'] = "username already exist, try with another one."

        except Exception as e:
            logging.error(e)

    context['title'] = 'Creation d un compte sur le site!'
    return render(request=request, template_name="accounts/signup.html", context=context)


def logout_user(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect('store:index')


def sign_in(request: HttpRequest) -> HttpResponse:
    context = {}
    # template = loader.get_template(template_name="accounts/login.html")
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('store:index')
            else:
                context['login_error'] = "username or password is invalid!!!"
                context['username'] = request.POST.get('username')
        except Exception as e:
            logging.error(e)

    context['title'] = 'login to your account'
    return render(request=request, template_name="accounts/login.html", context=context)

src/store/views.py
import logging

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.urls import reverse

from store.models import Product, Cart, Order


# Create your views here.
def index(request: HttpRequest) -> HttpResponse:
    products = Product.objects.all()
    return render(request=request, template_name="store/index.html", context={
        "title": "La boutique OK Fresh up",
        'products': products
    })


def product_detail(request, slug: str) -> HttpResponse:
    product = None
    try:
        product = Product.objects.get(slug=slug)
    except Exception as e:
        logging.error(e)
        return HttpResponse("Product not found!")
    return render(request=request, template_name="store/product_detail.html", context={
        'product': product,
        'title': product.name
    })


def add_to_cart(request: HttpRequest, slug: str) -> str:
    user = request.user
    product = get_object_or_404(Product, slug=slug)
    c, _ = Cart.objects.get_or_create(user=user)
    order, created = Order.objects.get_or_create(user=user,
                                                 ordered=False,
                                                 product=product)
    if created:
        c.orders.add(order)
        c.save()
    else:
        order.quantity += 1
        order.save()
    return redirect(reverse('store:product_detail', kwargs={'slug': slug}))


def cart(request: HttpRequest) -> HttpResponse:
    template = loader.get_template("store/cart.html")
    context = {}
    try:
        c = Cart.objects.get(user=request.user)
        context['cart'] = c
        context['title'] = f"{c.user.username} Liste des articles au panier"
    except Exception as e:
        logging.error(e)
        return HttpResponse('Cart not found')

    return HttpResponse(template.render(context, request))


def cart_delete(request: HttpRequest) -> HttpResponse:
    if c := request.user.cart:
        # c.orders.all().delete()
        c.delete()
    return redirect('store:index')

# def _add_to_cart(request: HttpRequest, slug: str) -> HttpResponse:
#     user = request.user
#     product = None
#     cart = None
#     order = None
#     try:
#         product = Product.objects.get(slug=slug)
#         if product:
#             cart = Cart.objects.get(user=user)
#             if cart:
#                 order = Order.objects.get(user__email=user.email, product__id=product.id)
#                 if order:
#                     cart.orders.add(order)
#                     cart.save()
#                 else:
#                     order.quantity += 1
#                     order.save()
#                 return redirect(reverse('store:product_detail', kwargs={'slug': slug}))
#
#     except Exception as e:
#         logging.error(e)
#         return HttpResponse('<h1>Object not found</h1>')

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block main %}
<h2>Se connecter</h2>
{% if login_error %}
<div class="alert alert-warning">
    {{ login_error }}
</div>
{% endif %}
<form action="{% url 'accounts:sign_in' %}" method="post">
    {% csrf_token %}
    <div class="form-wrapper">
        <label>Nom d'utilisateur</label>
        <input maxlength="100" minlength="5"
               name="username"
               placeholder="Nom d'utilisateur" value="{{ username }}">
    </div>
    <div class="form-wrapper">
        <label>Mot de passe</label>
        <input minlength="5" name="password" placeholder="Mot de passe du compte">
    </div>
    <div class="form-wrapper">
        <input maxlength="100" minlength="5"
               name="submit" type="submit" value="Se connecter">
    </div>
</form>
{% endblock %}

src/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block main %}
<h2>Sign up</h2>
{% if username_error %}
<div class="alert alert-warning">
    {{ username_error }}
</div>
{% endif %}
<form action="{% url 'accounts:sign_up' %}" method="post">
    {% csrf_token %}
    <div class="form-wrapper">
        <label>Nom d'utilisateur</label>
        <input maxlength="100" minlength="5" name="username" placeholder="Nom d'utilisateur">
    </div>
    <div class="form-wrapper">
        <label>Mot de passe</label>
        <input minlength="5" name="password" placeholder="Mot de passe du compte">
    </div>
    <div class="form-wrapper">
        <input maxlength="100" minlength="5"
               name="submit" type="submit" value="créer un compte">
    </div>
</form>
{% endblock %}

src/shop/templates/base.html
<!DOCTYPE html>
{% load tailwind_tags %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% tailwind_css %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
</head>
<body>

<h1 class="text-3xl font-bold text-green-400 ">
    La boutique de OK Fresh up
</h1>

<nav>
    <a href="{% url 'store:index' %}">Products</a>
    &nbsp;
    &nbsp;

    {% if not user.is_authenticated %}
    <a href="{% url 'accounts:sign_up' %}">Sing up</a>
    &nbsp;
    &nbsp;
    <a href="{% url 'accounts:sign_in' %}">se connecter</a>
    {% else %}
    <span>{{ user.username }} {{ user.email }}</span>
    <a href="{% url 'accounts:logout' %}">
        Déconnexion
    </a>
    {% endif %}
    {% if user.cart %}
    <p>
        <a href="{% url 'store:cart' %}">
            Voir le panier ( {{ user.cart.orders.count }} ) articles
        </a>
    </p>
    {% endif %}

</nav>

<div class="container-fluid">
    {% block main %}

    {% endblock %}
</div>


<footer>
    {% block footer %}

    {% endblock %}
</footer>

</body>
</html>

src/store/templates/store/cart.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block main %}
<h2>La liste des articles au panier de {{ cart.user.username }}</h2>
{% for order in cart.orders.all %}
<h3> {{ product.name }} </h3>
<img alt="{{ order.product.name }}" height="120" src="{{ order.product.thumbnail.url}}"
     width="120">
<p>{{ order.quantity }} {{ order.product.name }} en stock</p>
<p>
    <a href="{% url 'store:product_detail' slug=order.product.slug %}">Voir plus</a>
</p>
<p>
    <a href="{% url 'store:cart_delete' %}" onclick="return confirm('Etes-vous sure de vouloir vider le panier?')">Vider
        le panier</a>
</p>
{% endfor %}
{% endblock %}

src/store/templates/store/index.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block main %}
<h2>La liste des articles</h2>

<div class="columns-3">
    {% for product in products %}
        <h3> {{ product.name }} </h3>
            <img alt="{{ product.name }}" height="120" src="{{ product.thumbnail.url}}"
                 width="120">
            <p>Price {{ product.price }} $</p>
            <p>
                <a href="{% url 'store:product_detail' product.slug %}">Voir plus</a>
            </p>
        {% endfor %}
    {% endblock %}
</div>

src/store/templates/store/product_detail.html
{% extends "base.html" %}
{% block title %}
{{ title }}
{% endblock %}

{% block main %}
<h2>{{ product.name }}</h2>
<img alt="{{ product.name }}"
     height="120"
     src="{{ product.thumbnail.url}}"
     width="120">
<p>Price {{ product.price }}$ </p>
<p>{{ product.stock }} en stock </p>
<p>Description {{ product.description }}</p>
{% if user.is_authenticated %}
<p>
    <a href="{% url 'store:add_to_cart' slug=product.slug %}">
        Ajouter au panier
    </a>
    &nbsp;
    &nbsp;
    <a href="{% url 'store:cart' %}">
        Consulter mon panier
    </a>
</p>
{% endif %}
{% endblock %}

src/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Tailwind</title>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="ie=edge" http-equiv="X-UA-Compatible">
    {% tailwind_css %}
</head>

<body class="bg-gray-50 font-serif leading-normal tracking-normal">
<div class="container mx-auto">
    <section class="flex items-center justify-center h-screen">
        <h1 class="text-5xl">Django + Tailwind = ❤️</h1>
    </section>
</div>
</body>
</html>